### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by kination**
Fixed wrong typo `filnk`. Please look on.

### CODE REVIEW

**Comment by kination** [comment]
Also, there are few more bugs(or maybe I'm not doing it right...) in docs.
- There are no guide for `running a docker all in one image`. Is it missing?
- I couldn't create jar file with `mvn clean install` on repository. Do I have to run with flink?

**Comment by haohui** [comment]
It turns out that the typo also exists in `AthenaXConfiguration.java`. Can you please change that as well?

For your questions:

(1) Currently AthenaX requires plugging in your own CatalogProvider, thus packaging everything in a docker will not work out of the box. Having a docker image that can work out-of-the-box would be very nice.
(2) The jar file resides in `athenax-backend/target/` after you run `mvn clean install`.

**Comment by kination** [comment]
@haohui Thanks for notice! I updated it.

(1) That's okay, cause I'm not testing on docker yet. But in document, there are guide for `running a docker all in one image` and this link just goes on to starting guide. It seems something wrong.
(2) I couldn't find AthenaX-xxx.jar file below `/target`. In command line, it does not go after below.
```
2017-10-14 14:30:29,903 [ResourceManager Event Processor] WARN  capacity.LeafQueue (LeafQueue.java:activateApplications(632)) - maximum-am-resource-percent is insufficient to start a single application in queue, it is likely set too low. skipping enforcement to allow at least one application to start
2017-10-14 14:30:29,903 [ResourceManager Event Processor] WARN  capacity.LeafQueue (LeafQueue.java:activateApplications(653)) - maximum-am-resource-percent is insufficient to start a single application in queue for user, it is likely set too low. skipping enforcement to allow at least one application to start
2017-10-14 14:30:29,903 [ResourceManager Event Processor] INFO  capacity.LeafQueue (LeafQueue.java:activateApplications(667)) - Application application_1507959024479_0001 from user: kwangin activated in queue: default
2017-10-14 14:30:29,903 [ResourceManager Event Processor] INFO  capacity.LeafQueue (LeafQueue.java:addApplicationAttempt(683)) - Application added - appId: application_1507959024479_0001 user: org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.LeafQueue$User@4691abde, leaf-queue: default #user-pending-applications: 0 #user-active-applications: 1 #queue-pending-applications: 0 #queue-active-applications: 1
2017-10-14 14:30:29,904 [ResourceManager Event Processor] INFO  capacity.CapacityScheduler (CapacityScheduler.java:addApplicationAttempt(843)) - Added Application Attempt appattempt_1507959024479_0001_000001 to scheduler from user kwangin in queue default
2017-10-14 14:30:29,907 [AsyncDispatcher event handler] INFO  attempt.RMAppAttemptImpl (RMAppAttemptImpl.java:handle(815)) - appattempt_1507959024479_0001_000001 State change from SUBMITTED to SCHEDULED
2017-10-14 14:30:30,046 [main] INFO  impl.YarnClientImpl (YarnClientImpl.java:submitApplication(273)) - Submitted application application_1507959024479_0001
2017-10-14 14:30:30,057 [pool-11-thread-1] INFO  yarn.AthenaXYarnClusterDescriptor (AthenaXYarnClusterDescriptor.java:poll(282)) - Deploying cluster, current state ACCEPTED
2017-10-14 14:40:24,181 [Timer-3] INFO  scheduler.AbstractYarnScheduler (AbstractYarnScheduler.java:run(469)) - Release request cache is cleaned up
```
I waited about 30 minute, but process are not going on. Is it correct?

**Comment by SilverRainZ** [comment]
@djKooks `mvn install` runs along with tests and I don't know why the tests stops here, just use `mvn install -DskipTests` to skip ti. As mentioned at http://athenax.readthedocs.io/en/latest/getting_started/#start , the jar you need is located at `athenax-backend/target`.

**Comment by kination** [comment]
@SilverRainZ Thanks for advice! It works now.

**Pull request merged**
